[package]
name = "evenor"
version = "2.0.0"
description = "tell the story of your own data"
authors = ["fetsorn", "nasimmora"]
license = ""
repository = "https://gitlab.com/norcivilian-labs/evenor"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "evenor_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-shell = "2.0.0-beta"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
