#+TITLE: evenor
#+OPTIONS: toc:nil

Evenor - query and edit timelines. Tell the story of your own data.

* Developer Information and Tools
** Install dependencies
#+begin_quote
If you use [[https://nixos.org/][nix]], run `nix develop` to install all dependencies in PATH
#+end_quote

You'll need to install nodejs >= 18.15.0. We use yarn but npm should work too. Assuming that's done, run `yarn` with no args:

#+begin_src sh
yarn
#+end_src
** Build for desktop
#+begin_quote
If you use [[https://nixos.org/][nix]], run `nix build git+https://github.com/fetsorn/evenor#all`
#+end_quote

A desktop Electron app that stores data in a system folder.

#+begin_src sh
yarn start:electron

yarn build:electron
#+end_src
** Build for browser
#+begin_quote
If you use [[https://nixos.org/][nix]], run `nix build git+https://github.com/fetsorn/evenor#webapp`
#+end_quote

A React webapp that stores data in browser memory.

#+begin_src sh
yarn build:webapp
#+end_src
** Build for command-line
#+begin_quote
If you use [[https://nixos.org/][nix]], run `nix run git+https://github.com/fetsorn/evenor`
#+end_quote

A React webapp that stores data in current working directory.

#+begin_src sh
## build command-line service
yarn build:server

## get a sample csvs project
## from https://github.com/fetsorn/csvs-init.git
cd ~/csvs-init

## launch command-line
node path/to/evenor/src/server/index.js
#+end_src
* Documentation
Evenor stands for "EVENt editOR". In Greek, Evenor is the ancestor of the people of Atlantis. In tokien's elvish, evenor can be loosely translated as "common ground".
** Structure of the repo
[[src/renderer][renderer]] - a React app, packaged both as a webapp and as an Electron renderer

[[src-electron][src-electron]] - main Electron thread

[[src/server][server]] - a local ExpressJS server that serves the React app

[[src/lib][lib]] - common APIs
* Thanks
[[https://github.com/isomorphic-git/isomorphic-git][isomorphic-git]] - A pure JavaScript implementation of git for node and browsers

[[https://github.com/genea-app/genea-app][genea]] - Completely serverless solution for consuming and authoring GEDCOM genealogy data

[[https://github.com/vmiklos/ged2dot][ged2dot]] - GEDCOM to Graphviz converter

[[https://github.com/hpcc-systems/hpcc-js-wasm][hpcc-js-wasm]] - Graphviz compiled to WASM

[[https://github.com/electron-react-boilerplate/electron-react-boilerplate][electron-react-boilerplate]] - electron-builder with TypeScript and React

[[https://github.com/MatrixAI/TypeScript-Demo-Electron.git][@matrixai/typescript-demo-electron]] - electron-forge with TypeScript, Vue and Nix
