import { onZip } from "./record.js";
import {
  StoreContext,
  store,
  onRecordEdit,
  onRecordSave,
  onRecordWipe,
  onRecordCreate,
  onRepoChange,
  onSearch,
  setSpoilerOpen,
  getSpoilerOpen,
  getFilterQueries,
  getFilterOptions,
  getSortedRecords,
  onClone,
  onPullRepo,
  onPushRepo,
} from "./store.js";

export {
  StoreContext,
  store,
  onRecordEdit,
  onRecordSave,
  onRecordWipe,
  onRecordCreate,
  onRepoChange,
  onSearch,
  setSpoilerOpen,
  getSpoilerOpen,
  getFilterQueries,
  getFilterOptions,
  getSortedRecords,
  onZip,
  onClone,
  onPullRepo,
  onPushRepo,
};

export default {
  StoreContext,
  store,
  onRecordEdit,
  onRecordSave,
  onRecordWipe,
  onRecordCreate,
  onRepoChange,
  onSearch,
  setSpoilerOpen,
  getSpoilerOpen,
  getFilterQueries,
  getFilterOptions,
  getSortedRecords,
  onZip,
  onClone,
  onPullRepo,
  onPushRepo,
};
