import { onZip } from "./record.js";
import {
  StoreContext,
  store,
  onStartup,
  onRecordEdit,
  onRecordSave,
  onRecordWipe,
  onRecordCreate,
  onMindChange,
  onSearch,
  setSpoilerOpen,
  getSpoilerOpen,
  getFilterQueries,
  getFilterOptions,
  getSortedRecords,
  onClone,
  onPull,
  onPush,
} from "./store.js";

export {
  StoreContext,
  store,
  onStartup,
  onRecordEdit,
  onRecordSave,
  onRecordWipe,
  onRecordCreate,
  onMindChange,
  onSearch,
  setSpoilerOpen,
  getSpoilerOpen,
  getFilterQueries,
  getFilterOptions,
  getSortedRecords,
  onZip,
  onClone,
  onPull,
  onPush,
};

export default {
  StoreContext,
  store,
  onStartup,
  onRecordEdit,
  onRecordSave,
  onRecordWipe,
  onRecordCreate,
  onMindChange,
  onSearch,
  setSpoilerOpen,
  getSpoilerOpen,
  getFilterQueries,
  getFilterOptions,
  getSortedRecords,
  onZip,
  onClone,
  onPull,
  onPush,
};
