declare module "*.module.css";
declare module "@fetsorn/csvs-js";
declare module "@fetsorn/ged2dot";
declare module "docx4js";
declare module "word-extractor";
declare module "cfb";
declare module "@fetsorn/ppt";
declare module "file-saver";
declare module "@isomorphic-git/lightning-fs";
